name: socket_client_real_adapter
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  socket_client:
    path: ../
  core:
    path: ../../core
  network_client:
    path: ../../network_client/
  signalr_netcore: ^1.3.6
  colorize: ^3.0.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
