name: shared_dependencies
description:
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  shared_preferences: ^2.2.1
  # flutter_background_service: ^5.0.1
  # flutter_background_service_android: ^6.0.1
  flutter_local_notifications: ^15.1.1
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  go_router: ^12.0.1
  intl: ^0.18.1
  get_storage: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
