name: biker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./packages/core
  domain:
    path: ./packages/domain
  dialog_api:
    path: ./packages/dialog_api
  formatter_api:
    path: ./packages/formatter_api
  network_client:
    path: ./packages/network_client
  network_client_real_adapter:
    path: ./packages/network_client/network_client_real_adapter
  authentication:
    path: ./packages/authentication
  biker_info:
    path: ./packages/biker_info
  geo_locator:
    path: ./packages/geo_locator
  geo_locator_api:
    path: ./packages/geo_locator_api
  local_storage:
    path: ./packages/local_storage
  localization_api:
    path: ./packages/localization_api
  notification:
    path: ./packages/notification
  order:
    path: ./packages/order
  resource_strings:
    path: ./packages/resource_strings
  schedule:
    path: ./packages/schedule
  secure_local_storage:
    path: ./packages/secure_local_storage
  service_locator:
    path: ./packages/service_locator
  shared_dependencies:
    path: ./packages/shared_dependencies
  sms:
    path: ./packages/sms
  env_jar:
    path: ./packages/env_jar
  image_picker_api:
    path: ./packages/image_picker_api
  token_jar:
    path: ./packages/token_jar
  ui_kit:
    path: ./packages/ui_kit
  validator_api:
    path: ./packages/validator_api
  mm_phone_number_validator:
    path: ./packages/mm_phone_number_validator
  app_state:
    path: ./packages/app_state
  app_state_notifier:
    path: ./packages/app_state_notifier
  resend_pin_button:
    path: ./packages/resend_pin_button
  extensions:
    path: ./packages/extensions
  

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  get: ^4.6.6
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  collection: ^1.17.2
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.1
  get_storage: ^2.1.1
  pinput: ^3.0.1
  lottie: ^2.7.0
  colorize: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  go_router: ^12.0.1
  pretty_dio_logger: ^1.3.1
  http: ^0.13.3
  modal_bottom_sheet: ^2.1.2
  virtual_keyboard_multi_language: ^1.0.3
  animate_do: ^3.1.2
  audioplayers: ^5.2.0
  image_picker: ^1.0.4
  signalr_netcore: ^1.3.3
  file_picker: ^6.1.1
  firebase_messaging: ^14.7.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.3
  flutter_shake_animated: ^0.0.5
  bouncing_widget: ^2.0.0
  flutter_map: ^4.0.0
  bloc_concurrency: ^0.2.2
  latlong2: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/lotties/
    - assets/images/
    - assets/images/permission/
    - assets/call/
    - assets/images/payments/
    - assets/audiofiles/
