name: sms
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core
  token_jar:
    path: ../token_jar
  dialog_api:
    path: ../dialog_api
  localization_api:
    path: ../localization_api
  resource_strings:
    path: ../resource_strings
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0