name: app_state
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core
  domain:
    path: ../domain
  data:
    path: ../data
  geo_locator:
    path: ../geo_locator
  biker_info:
    path: ../biker_info
    
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  bloc: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^2.0.0
  melos: ^3.2.0
  test: ^1.21.0
