name: biker_notificatoin_socket
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  notification:
    path: ../notification
  local_storage:
    path: ../local_storage/
  network_client:
    path: ../network_client/
  socket_client:
    path: ../socket_client/
  socket_client_real_adapter:
    path: ../socket_client/socket_client_real_adapter/
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
