name: token_jar
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core
  domain:
    path: ../domain
  data:
    path: ../data
  secure_local_storage:
    path: ../secure_local_storage
  authentication:
    path: ../authentication

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0