name: notification
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  drift: ^2.11.1
  path_provider: ^2.1.1
  dio: ^5.3.3
  get_it: ^7.6.4
  bloc: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
  drift_dev: ^2.6.0


