name: env_jar
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  envied: ^0.5.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.1
  lints: ^2.0.0
  test: ^1.21.0
