name: extensions
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  domain:
    path: ../domain
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0