name: image_picker_api
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core
  cross_file: ^0.3.3+8
  image_picker: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0