name: geo_locator_api
description:
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  core:
    path: ../core
  geolocator: ^10.1.0
  latlong2: ^0.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0