name: service_locator
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  local_storage:
    path: ../local_storage

  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
